# Site settings
title: Hello world!
header-img: img/home-bg.png
email: kriti.rai@gmail.com
copyright_name: kriti-rai
description: > # this means to ignore newlines until "baseurl:"
  Beginning of the journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kriti-rai
learn_profile: kriti-rai
email_username: kriti.rai@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
